const INDUSTRY_BY_TICKER: Record<string, string> = {
  HDFCBANK: "banking",
  ICICIBANK: "banking",
  KOTAKBANK: "banking",
  SBIN: "banking",
  AXISBANK: "banking",
  INDUSINDBK: "banking",
  BANDHANBNK: "banking",
  FEDERALBNK: "banking",
  BAJFINANCE: "banking",
  BAJAJFINSV: "banking",
  MUTHOOTFIN: "banking",
  CHOLAFIN: "banking",
  SUNPHARMA: "pharma",
  DRREDDY: "pharma",
  CIPLA: "pharma",
  DIVISLAB: "pharma",
  BIOCON: "pharma",
  TCS: "technology",
  INFY: "technology",
  WIPRO: "technology",
  HCLTECH: "technology",
  TECHM: "technology",
  LTIM: "technology",
  COFORGE: "technology",
  MARUTI: "automobiles",
  TATAMOTORS: "automobiles",
  "M&M": "automobiles",
  "BAJAJ-AUTO": "automobiles",
  HEROMOTOCO: "automobiles",
  TVSMOTORS: "automobiles",
  EICHERMOT: "automobiles",
  RELIANCE: "energy",
  ONGC: "energy",
  IOC: "energy",
  BPCL: "energy",
  GAIL: "energy",
  POWERGRID: "energy",
  NTPC: "energy",
  DLF: "real-estate",
  GODREJPROP: "real-estate",
  OBEROIRLTY: "real-estate",
  PHOENIXLTD: "real-estate",
  PRESTIGE: "real-estate",
  SOBHA: "real-estate",
  HINDUNILVR: "consumer",
  ITC: "consumer",
  NESTLEIND: "consumer",
  BRITANNIA: "consumer",
  DABUR: "consumer",
  MARICO: "consumer",
  TATASTEEL: "metals-mining",
  JSWSTEEL: "metals-mining",
  HINDALCO: "metals-mining",
  VEDL: "metals-mining",
  COALINDIA: "metals-mining",
  SIEMENS: "manufacturing",
  ABB: "manufacturing",
  HAVELLS: "manufacturing",
  VOLTAS: "manufacturing",
  DELHIVERY: "logistics",
  BLUEDART: "logistics",
  GATI: "logistics",
  ALLCARGO: "logistics",
};

export function inferIndustrySlugFromTicker(ticker: string): string | null {
  const clean = ticker.toUpperCase().replace(".NS", "");
  return INDUSTRY_BY_TICKER[clean] ?? null;
}
